Handle maillist errors in pacupdate

diff --git a/.local/bin/pacupdate b/.local/bin/pacupdate
--- a/.local/bin/pacupdate
+++ b/.local/bin/pacupdate
@@ -202,7 +202,7 @@ function check_update_pacman_mirrorlist
         return 0
     end
 
-    update_pacman_mirrorlist; or return 1
+    update_pacman_mirrorlist || return 1
 end
 
 
@@ -219,10 +219,8 @@ function update_pacman_mirrorlist
     sed -i 's/^#Server/Server/' "$mirrorlist_temp"
 
     # backing up the old mirrorlist and setting the new one in place
-    sudo cp /etc/pacman.d/mirrorlist /etc/pacman.d/mirrorlist.backup
-        or return 1
-    sudo mv $mirrorlist_temp /etc/pacman.d/mirrorlist
-        or return 1
+    sudo cp /etc/pacman.d/mirrorlist /etc/pacman.d/mirrorlist.backup || return 1
+    sudo mv $mirrorlist_temp /etc/pacman.d/mirrorlist || return 1
     echo_important "Mirrorlist updated."
 end
 
@@ -240,13 +238,16 @@ function check_mailing_list
 
     # get most recent message id from arch mailing list
     set msg_id_list (string match -r '(?<=^Message-ID: <)[^>]+' < $mail_list_file)
+    or begin
+        set_color -o; echo "Error. Server returned the following as mailing list:"; set_color normal
+        cat $mail_list_file
+        yn_prompt "Continue anyway?" && return 0 || return 1
+    end
 
     if [ -z $last_update_msg_id ]
         set_cache_var last_update_msg_id $msg_id_list[-1]
         echo "There are no previously recorded visits to the Arch Mailing List."
-        yn_prompt "Continue anyway?"
-            and return 0
-            or return 1
+        yn_prompt "Continue anyway?" && return 0 || return 1
     else if [ $last_update_msg_id = $msg_id_list[-1] ]
         echo_important "No news."
         return
@@ -260,9 +261,7 @@ function check_mailing_list
             confirm 'Press Enter to continue.'
         end
         set_cache_var last_update_msg_id $msg_id_list[-1]
-        yn_prompt "Continue with the updating process?"
-            and return 0
-            or return 1
+        yn_prompt "Continue with the updating process?" && return 0 || return 1
     end
 end
 
@@ -280,15 +279,14 @@ function get_package_buildtime -a pkg
 
     pacman -Qi $pkg | \
     string replace -rf 'Build Date\s+:\s+(.+)$' '$1' | \
-    read -l builddate_time
-        or return 1
+    read -l builddate_time || return 1
     date -d $builddate_time +%s
 end
 
 
 function check_git_package_schedule -a pkg
     # check if a git package is scheduled for an update check
-    set last_check (get_cache_var "$pkg-checkdate"; or echo 0)
+    set last_check (get_cache_var "$pkg-checkdate" || echo 0)
     set last_update (get_package_buildtime $pkg)
     set check_interval (math $PACUPDATE_GIT_INTERVAL \* 86400) # convert to seconds
 
@@ -321,8 +319,7 @@ end
 
 function retrieve_git_fragment -a vcs_url frag fallback
     # extract fragment from vcs_url or fall back to $fallback
-    string replace -rf '^[^#]+#.*'$frag'=(.+?)(#|$)' '$1' $vcs_url
-        or echo $fallback
+    string replace -rf '^[^#]+#.*'$frag'=(.+?)(#|$)' '$1' $vcs_url || echo $fallback
 end
 
 
@@ -357,8 +354,7 @@ function get_last_git_commit -a git_url
         end
 
     # this is the return value
-    git -C "$git_dir" log -1 --format=format:%h
-        or return 1
+    git -C "$git_dir" log -1 --format=format:%h || return 1
 end
 
 
@@ -366,8 +362,7 @@ function check_git_package -a pkg
     # check a single git package for updates and return without status if there are any
 
     # skip immediately if it's not time for a check yet
-    check_git_package_schedule $pkg
-        or return 1
+    check_git_package_schedule $pkg || return 1
 
     echo "Checking updates for $pkg..."
     set git_url (get_git_url $pkg)
@@ -391,8 +386,7 @@ end
 
 function check_repo_updates
     echo_head "Updates in Pacman's repos?"
-    sudo pacman -Sy > /dev/null
-        or return 1
+    sudo pacman -Sy > /dev/null || return 1
     set repo_updates (pacman -Quq)
     set repo_updates_count (count $repo_updates)
 
@@ -408,8 +402,7 @@ function check_aur_updates
     echo_head "Updates in the AUR?"
 
     # skip if auracle's not installed
-    test_installed auracle
-        or return 0
+    test_installed auracle || return 0
 
     for pkg in (auracle sync -q)
         # this is for packages that get moved from the aur to the official repos
@@ -429,13 +422,12 @@ function check_git_updates
     echo_head "Outdated git-packages?"
 
     # skip if git's not installed
-    test_installed git
-        or return 0
+    test_installed git || return 0
 
     set git_pkgs (pacman -Qq | string match -er -- '-git$')
     for pkg in $git_pkgs
         if not contains $pkg $aur_updates
-            check_git_package $pkg; or continue
+            check_git_package $pkg || continue
 
             set -a git_updates $pkg
         end
@@ -465,18 +457,14 @@ end
 
 function install_repo_updates
     # skip if there are no updates
-    [ $repo_updates_count -gt 0 ]
-        or return 0
+    test $repo_updates_count -gt 0 || return 0
 
-    set pacman_log (string replace -rf '^LogFile\s+=\s+(\S+)' '$1' < /etc/pacman.conf
-        or echo "/var/log/pacman.log")
+    set pacman_log (string replace -rf '^LogFile\s+=\s+(\S+)' '$1' < /etc/pacman.conf || echo "/var/log/pacman.log")
     set pacman_old_log (mktemp --suffix=".log.old")
-    cp $pacman_log $pacman_old_log
-        or return 1
+    cp $pacman_log $pacman_old_log || return 1
 
     echo_head "Installing updates from Pacman's repos..."
-    sudo pacman -Su
-        or return 1
+    sudo pacman -Su || return 1
 
     get_warnings_from_log $pacman_old_log $pacman_log
     # TODO: process new log entries -- test
@@ -494,40 +482,34 @@ function build_aur_pkg
             echo "Error retrieving package $_flag_pkg from AUR." >&2
             return 1
         end
-    makepkg -sri $makepkg_args
-        or return 1
+    makepkg -sri $makepkg_args || return 1
 end
 
 
 function install_aur_updates
     # skip if there are no aur_updates
-    [ $aur_updates_count -gt 0 ]
-        or return 0
+    test $aur_updates_count -gt 0  || return 0
 
     echo_head "Installing updates from the AUR..."
 
     # skip if git's not installed
-    test_installed git
-        or return 0
+    test_installed git || return 0
 
     for aur_pkg in $aur_updates
         aurmake $aur_pkg
-            or yn_prompt "Error installing $aur_pkg. Continue anyway? "
-                or return 1
+            or yn_prompt "Error installing $aur_pkg. Continue anyway? " || return 1
     end
 end
 
 
 function install_git_updates
-    [ $git_updates_count -gt 0 ]
-        or return 0
+    test $git_updates_count -gt 0  || return 0
 
     echo_head "Installing Git updates..."
 
     for pkg in $git_updates
         aurmake -f $pkg
-            or yn_prompt "Error installing $aur_pkg. Continue anyway? "
-                or return 1
+            or yn_prompt "Error installing $aur_pkg. Continue anyway? " || return 1
     end
 end
 
@@ -539,14 +521,10 @@ function install_updates
         return 0
     end
 
-    yn_prompt "Install total of $total_updates_count updates?"
-        or return 1
-    install_repo_updates
-        or return 1
-    install_aur_updates
-        or return 1
-    install_git_updates
-        or return 1
+    yn_prompt "Install total of $total_updates_count updates?" || return 1
+    install_repo_updates || return 1
+    install_aur_updates || return 1
+    install_git_updates || return 1
 end
 
 
